INSERT INTO Books (Title, Author, Price) VALUES
('Clean Code', 'Robert C. Martin', 250),
('The Pragmatic Programmer', 'Andrew Hunt', 270),
('Design Patterns', 'Erich Gamma', 300),
('Refactoring', 'Martin Fowler', 320),
('Code Complete', 'Steve McConnell', 280),
('Head First Java', 'Kathy Sierra', 220),
('Effective Java', 'Joshua Bloch', 260),
('Java: The Complete Reference', 'Herbert Schildt', 240),
('Introduction to Algorithms', 'Cormen', 350),
('Operating System Concepts', 'Silberschatz', 330),
('Database System Concepts', 'Korth', 310),
('Computer Networking', 'Kurose', 300),
('Artificial Intelligence: A Modern Approach', 'Russell', 400),
('Data Structures Using C', 'Seymour Lipschutz', 200),
('Python Crash Course', 'Eric Matthes', 230),
('Automate the Boring Stuff with Python', 'Al Sweigart', 210),
('Learning SQL', 'Alan Beaulieu', 190),
('SQL Fundamentals', 'John J. Patrick', 180),
('Modern Operating Systems', 'Andrew Tanenbaum', 340),
('Computer Organization and Design', 'Patterson', 360),
('Digital Design', 'M. Morris Mano', 250),
('Programming in C', 'Dennis Ritchie', 170),
('C Programming Language', 'Kernighan', 200),
('Introduction to C++', 'Stroustrup', 260),
('Object-Oriented Programming in C++', 'Robert Lafore', 240),
('C# Programming Yellow Book', 'Rob Miles', 210),
('ASP.NET Core Guide', 'Microsoft', 280),
('Web Development with Node.js', 'Andrew Mead', 230),
('React Explained', 'Zac Gordon', 220),
('Learning React', 'Alex Banks', 240),
('HTML and CSS Design', 'Jon Duckett', 180),
('JavaScript: The Good Parts', 'Douglas Crockford', 200),
('Eloquent JavaScript', 'Marijn Haverbeke', 190),
('You Don’t Know JS', 'Kyle Simpson', 210),
('PHP & MySQL', 'Larry Ullman', 200),
('Laravel Up & Running', 'Matt Stauffer', 250),
('Django for Beginners', 'William Vincent', 230),
('Flask Web Development', 'Miguel Grinberg', 220),
('Machine Learning Basics', 'Andrew Ng', 300),
('Deep Learning', 'Ian Goodfellow', 380),
('Hands-On Machine Learning', 'Aurélien Géron', 350),
('Data Science from Scratch', 'Joel Grus', 270),
('Big Data Analytics', 'Viktor Mayer', 320),
('Cloud Computing Concepts', 'Rajkumar Buyya', 300),
('AWS Essentials', 'Amazon Web Services', 260),
('Azure Fundamentals', 'Microsoft', 250),
('Cyber Security Basics', 'William Stallings', 290),
('Network Security Essentials', 'William Stallings', 280),
('Cryptography and Network Security', 'Behrouz Forouzan', 300),
('Ethical Hacking Guide', 'Georgia Weidman', 270),
('Linux Basics', 'Richard Blum', 180),
('UNIX Programming', 'Kernighan', 200),
('Shell Scripting Guide', 'Steve Parker', 190),
('Docker Deep Dive', 'Nigel Poulton', 240),
('Kubernetes in Action', 'Marko Luksa', 320),
('Git Pro Book', 'Scott Chacon', 200),
('Version Control with Git', 'Jon Loeliger', 210),
('Software Engineering', 'Ian Sommerville', 330),
('System Design Interview', 'Alex Xu', 260),
('Cracking the Coding Interview', 'Gayle Laakmann', 300),
('LeetCode Patterns', 'Sean Prashad', 220),
('Algorithms Unlocked', 'Cormen', 250),
('Programming Challenges', 'Skiena', 270),
('Mathematics for CS', 'Lehman', 280),
('Discrete Mathematics', 'Rosen', 260),
('Linear Algebra Done Right', 'Axler', 240),
('Probability and Statistics', 'Walpole', 230),
('Statistics for Data Science', 'James', 250),
('AI for Everyone', 'Andrew Ng', 180),
('Python for Data Analysis', 'Wes McKinney', 220),
('Pandas Cookbook', 'Ted Petrou', 200),
('NumPy Guide', 'Travis Oliphant', 190),
('Matplotlib Essentials', 'John Hunter', 180),
('Deep Learning with Python', 'François Chollet', 300),
('Computer Vision Basics', 'Richard Szeliski', 320),
('Natural Language Processing', 'Jurafsky', 340),
('Speech and Language Processing', 'Daniel Jurafsky', 350),
('Reinforcement Learning', 'Sutton', 360),
('Game Development with Unity', 'Joseph Hocking', 250),
('Unreal Engine Guide', 'William Sherif', 260),
('Mobile App Development', 'Mark Murphy', 230),
('Android Programming', 'Bill Phillips', 240),
('iOS Development Swift', 'Apple', 250),
('Swift Programming', 'Apple', 220),
('Kotlin in Action', 'Dmitry Jemerov', 240),
('Go Programming Language', 'Alan Donovan', 260),
('Rust Programming', 'Steve Klabnik', 270),
('Haskell Programming', 'Graham Hutton', 250),
('Scala for Beginners', 'Martin Odersky', 240),
('Big Data with Hadoop', 'Tom White', 300),
('Spark in Action', 'Jean-Georges Perrin', 310),
('Data Engineering Guide', 'Maxime Beauchemin', 280),
('DevOps Handbook', 'Gene Kim', 290),
('Site Reliability Engineering', 'Google', 320),
('Clean Architecture', 'Robert C. Martin', 300),
('Microservices Design', 'Sam Newman', 310),
('System Architecture Basics', 'Mark Richards', 280),
('Software Testing Basics', 'Paul Ammann', 220),
('QA Engineering Guide', 'James Bach', 200);
